### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by nikeTion** [okx-code/Rankup3#12]
> [11:51:54] [pool-2-thread-1/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.requirements.Requirement.setValue(Requirement.java:38)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.requirements.RequirementRegistry.newRequirement(RequirementRegistry.java:19)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.requirements.RequirementRegistry.getRequirements(RequirementRegistry.java:33)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.ranks.Rank.deserialize(Rank.java:36)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.ranks.Rankups.lambda$new$0(Rankups.java:9)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.RankList.<init>(RankList.java:28)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.ranks.Rankups.<init>(Rankups.java:9)
> [11:51:54] [pool-2-thread-1/WARN]: 	at sh.okx.rankup.Rankup.refreshRanks(Rankup.java:185)
> [11:51:54] [pool-2-thread-1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> [11:51:54] [pool-2-thread-1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
> [11:51:54] [pool-2-thread-1/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:768)
> [11:51:54] [pool-2-thread-1/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:342)
> [11:51:54] [pool-2-thread-1/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:705)
> [11:51:54] [pool-2-thread-1/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$startTickloop$0(MinecraftServer.java:592)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [11:51:54] [pool-2-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
> [11:51:54] [pool-2-thread-1/INFO]: [Rankup] Disabling Rankup v3.5.2
> [11:51:54] [pool-2-thread-1/ERROR]: [Rankup] Could not finish enabling Rankup

My config rankups.yml:

 #https://github.com/okx-code/Rankup3/wiki/Requirements
 rank1:
   rank: 'Stone'
   next: 'Coal'
   requirements:
     - 'playtime-minutes 60'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 1 ora di gioco.'
 rank2:
   rank: 'Coal'
   next: 'Iron'
   requirements:
     - 'playtime-minutes 180'
     - 'money 1500'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 1500money, 3 ore di gioco.'
 rank3:
   rank: 'Iron'
   next: 'Glowstone'
   requirements:
     - 'playtime-minutes 300'
     - 'money 2500'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 2500money, 5 ore di gioco.'
 rank4:
   rank: 'Glowstone'
   next: 'Slime'
   requirements:
     - 'playtime-minutes 480'
     - 'money 4500'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 4500money, 8 ore di gioco.'
 rank5:
   rank: 'Slime'
   next: 'Lapis'
   requirements:
     - 'playtime-minutes 600'
     - 'player-kills 20'
     - 'money 8000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 8000money, 10 ore di gioco, 20 uccisioni.'
 rank6:
   rank: 'Lapis'
   next: 'Redstone'
   requirements:
     - 'playtime-minutes 780'
     - 'money 125000'
     - 'mob-kills 300'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 12500money, 13 ore di gioco, 300 mob uccisi.'
 rank7:
   rank: 'Redstone'
   next: 'Gold'
   requirements:
     - 'playtime-minutes 1080'
     - 'money 25000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 25000money, 18 ore di gioco.'
 rank8:
   rank: 'Gold'
   next: 'Obsidian'
   requirements:
     - 'playtime-minutes 1440'
     - 'money 50000'
     - 'player-kills 100'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 50000money, 1 giorno di gioco, 100 uccisioni.'
 rank9:
   rank: 'Obsidian'
   next: 'Prismarine'
   requirements:
     - 'playtime-minutes 2160'
     - 'money 100000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 100000money, 1 giorno di gioco e 12 ore.'
 rank10:
   rank: 'Prismarine'
   next: 'Emerald'
   requirements:
     - 'playtime-minutes 2880'
     - 'money 200000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 200000money, 2 giorni di gioco.'
 rank11:
   rank: 'Emerald'
   next: 'Quartz'
   requirements:
     - 'playtime-minutes 3600'
     - 'money 400000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 400000money, 2 giorni di gioco e 12 ore.'
 rank12:
   rank: 'Quartz'
   next: 'Diamond'
   requirements:
     - 'playtime-minutes 4320'
     - 'money 800000'
     - 'mob-kills 2000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 800000money, 3 giorni di gioco, 2000 mob uccisi.'
 rank13:
   rank: 'Diamond'
   next: 'Bedrock'
   requirements:
     - 'playtime-minutes 7200'
     - 'money 1600000'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 1600000money, 5 giorni di gioco.'
 rank14:
   rank: 'Bedrock'
   next: 'Ender'
   requirements:
     - 'playtime-minutes 10080'
     - 'money 3200000'
     - 'player-kills 750'
   rankup:
     requirements-not-met: '&a[✕] &fRequisiti:&e 3200000money, 1 settimana di gioco, 750 uccisioni.'

**Comment by okx-code** [comment]
```
 - 'mob-kills 2000'
``` 
You msut specify a mob name here
