### ISSUE TITLE
Sorry, nut we could not find any rankups for the group(s) you are in. Use /ranks to list the rankups! error

### ISSUE THREAD

**Issue by XipsAhoy** [okx-code/Rankup3#14]
My problem is that I don´t now how fix this!

**Comment by okx-code** [comment]
Issues are for bugs within Rankup. Join the Discord https://discord.gg/hmzGJzu

**Comment by xJoshuaLR** [comment]
I have the same problem and I don't know why if I have some 20 ranges created

**Comment by xJoshuaLR** [comment]
help me please
