### ISSUE TITLE
Rankup overwriting secondary Pex ranks

### ISSUE THREAD

**Issue by TheDaedraGamer** [okx-code/Rankup3#16]
Hello, I have encountered an issue on my server. When one does /rankup it seems to clear all the groups that person is in and then moves them to the rankup rank designated. This is making it difficult for me to add Staff /Donator's and other such things

**Comment by okx-code** [comment]
Rankup does not clear the group a player is in - this is an error on your part. You can see this in [the code](https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/Rankup.java#L331-L332).

**Comment by TheDaedraGamer** [comment]
Well in that case may I post the rankup config and to try and learn what I did wrong?

**Comment by okx-code** [comment]
Issues are for errors with the plugin, join the discord for support https://discord.gg/maB4382
