### ISSUE TITLE
'votingplugin-votes' requirement isn't working 

### ISSUE THREAD

**Issue by Renellin** [okx-code/Rankup3#23]
I have votingplugin and its working. Rankup works for other requirements, except for voting. The voting requirement is added as  'votingplugin-votes 10'.  I tried both {PERCENT_DONE votingplugin-votes} and {AMOUNT_NEEDED votingplugin-votes}, both show 0, regardless. They both show the number done at 0% or 10 still needed, and not broken placeholder.
Here is the code by Okx.
 https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/requirements/requirement/votingplugin/VotingPluginVotesRequirement.java

**Comment by okx-code** [comment]
I cannot reproduce this issue.
