### ISSUE TITLE
Featherboard module error?

### ISSUE THREAD

**Issue by lucas2107** [okx-code/Rankup3#24]
Hello,

I've an error generated by Featherboard when I add your plugin to my server.
Here is the error: https://file.properties/paste/satudonifu.md
I don't know if the problem come from your plugin or from Featherboard.

Let me know if I need to contact the Featherboard dev.

Best regards,

**Comment by okx-code** [comment]
This is not created by rankup, you might need to contact the FeatherBoard developer.
