### ISSUE TITLE
More options to edit ranks

### ISSUE THREAD

**Issue by Zanderless** [okx-code/Rankup3#26]
Just to quickly put it, I've spent half an hour attempting to edit the rank names shown so they will show the correct name I want to show, including capital letters, but I've found no actual way to do it, even using Placeholder API and javascript, I couldn't find a way to do it.

Problem I have found:
The only way to actually get the old rank and next rank for each category is through {RANK} and {OLD_RANK}
{OLD_RANK_NAME} and {RANK_NAME} don't work, but are included in your placeholders

I just hope that I'm missing something. But anyways, great plugin

**Comment by Zanderless** [comment]
I did see you updated the wiki page removing OLD_RANK_NAME and RANK_NAME

**Comment by okx-code** [comment]
If you are using the rank names in /ranks, you can edit the /ranks entry for each individual rank to show what you want, but it will require some copy-pasting.
