### ISSUE TITLE
Problem with Prestage sub requirements

### ISSUE THREAD

**Issue by RomanSilhan** [okx-code/Rankup3#33]
A:
  rank: 'A'
  next: 'B'
  requirements:
    default: # used when a player hasn't prestiged
      - 'money 100'
    p1: # used in p1
      - 'money 200'
    p2: # used in p2
      - 'money 300'

I dont know if it is old config but in console: [ERROR] [Rankup] Rankup/prestige section 'A' is using the old requirements system.
08:19:34[ERROR] [Rankup] Instead of a configuration section, it is now a list of strings.
08:19:34[ERROR] [Rankup] For example, instead of "requirements: money: 1000" you should use "requirements: - 'money 1000'".

With config just like this: 
A:
  rank: 'A'
  next: 'B'
  requirements:
    - 'money 100

Works
Ty for help :)

**Comment by okx-code** [comment]
Support is on the discord server, this is for bugs and feature requests
