### ISSUE TITLE
Enhancement: sound and effects + requirements colors +rank overview

### ISSUE THREAD

**Issue by kristouffe** [okx-code/Rankup3#35]
Hi, no way to submit a feature request, so i post it as an issue. Sorry for that.

Would be great to be able to play sounds and/or visual effects on players location after a rankup. I know about commands runned when a player ranks up. But it makes it a bit tricky when it comes to sounds and visual effects since we can't get the players location. Would be easier to have sound and effect IDs custumizable in rankup.yml.

Another problem i have, is that there is no way actually to make a difference between the requirements who are met and the ones who are not met yet, when you have multiple requirements for a rank up. 
Imagine I need 64 Stone and 1000 money to rankup. I already have the 1000 money but not the 64 Stone. In requirements-not-met i have ; 
&c{AMOUNT_DONE item#stone}&f/&a{AMOUNT item#stone} Stone
&c{AMOUNT_DONE money}&f/&a{MONEY}€
Would it be possible to change the text  of AMOUNT_DONE once it mets the total amount requirement to finally get:
**Example:**
**what it does:**
32(red)/64(green) Stone
1000(red)/1000(green)€
**what i want it to do:**
32(red)/64(green) Stone
1000(green)/1000(green)€
I guess we simply need for each requirement a customizable text once the requirement is done, and one custromizable text once the requirement isn't done yet/in progress.

**Last point**, could you maybe add a customizable gui to get an overview of all ranks, being able to show what permissions/rights each ranks gives and what they cost.

thank you very much :)
nice plugin though

**Comment by flurbudurbur** [comment]
I'm happy to say that everything you're suggesting/asking for is now something we can do (is some way or another)!

sound and/or visual effects:
```yaml
  commands:
    - 'execute at {PLAYER} run playsound minecraft:ui.toast.challenge_complete player {PLAYER} ~ ~ ~'
    - 'execute at {PLAYER} run particle minecraft:firework ~ ~1 ~ 1 1 1 0 30 normal'
    - 'title {PLAYER} subtitle {"text":"Congratulations!","bold":true,"color":"aqua"}'
    - 'title {PLAYER} title {"text":"Ranked up!","bold":true,"color":"light_purple"}'
```
**note: made for 1.16**

Changing requirement color when complete:
> Tutorial on our wiki
> https://github.com/okx-code/Rankup3/wiki/Advanced-Configuration-Example#change-requirement-chat-color-when-completed

Customizable GUI:
> Since the Rankup 3.10 update, there's been a ranksGUI available
> Link to config file with highlighted line so you can find the toggle
https://github.com/okx-code/Rankup3/blob/49942e5497de6da0c5fd20fe4deed2fd49620bc9/src/main/resources/config.yml#L25
> Tutorial on how to add lore
> https://github.com/okx-code/Rankup3/wiki/Advanced-Configuration-Example#adding-lore-to-ranksgui
