### ISSUE TITLE
Playtime plugin

### ISSUE THREAD

**Issue by LoneDevilX** [okx-code/Rankup3#39]
Hello author,

May I know can the rankup plugin link/support to others playtime plugin rather than the essentials or worlds'? This is the plugin link: https://www.spigotmc.org/resources/playtime-%C2%BB-1-7-1-15-2-%E2%80%A2-fully-configurable.44852/

Thank you

**Comment by okx-code** [comment]
A playtime plugin that supported SQL would be better I think

**Comment by okx-code** [comment]
This is not planned to be added
