### ISSUE TITLE
Plugin does not show play time. 

### ISSUE THREAD

**Issue by kalleswe** [okx-code/Rankup3#41]
If the plugin tracks playtime, it should also be able to print that for players with a command.
Should be a simple sendMessage call. DO NOT CLOSE THIS UNTIL FIXED.

**Comment by okx-code** [comment]
This would probably be best when playtime is added from its own plugin that counts it, instead of Minecraft statistics

**Comment by okx-code** [comment]
Fixed in the latest pre release on the discord
