### ISSUE TITLE
Tokens plugin support

### ISSUE THREAD

**Issue by tibika10** [okx-code/Rankup3#42]
Hello!
My server is version 1.16 and I wish I could use the Tokens plugin - (link: https: //www.spigotmc.org/resources/tokens-multi-plugin-support-mysql-support.71941/) as a requirement for rankUp ! The token manager plugin is not being updated for a1.16 so far! thanks

**Comment by flurbudurbur** [comment]
This plugin supports PlaceholderAPI, which means that it can already be used as a requirement.

Check out this section of our wiki for the tutorial:
https://github.com/okx-code/Rankup3/wiki/Advanced-Configuration-Example#how-to-implement-custom-requirements
