### ISSUE TITLE
Request for placeholder upgrade

### ISSUE THREAD

**Issue by LoneDevilX** [okx-code/Rankup3#44]
https://pastebin.ubuntu.com/p/C9nK5FmmDM/

**Comment by okx-code** [comment]
What version of Rankup are you using?

**Comment by LoneDevilX** [comment]
![image](https://user-images.githubusercontent.com/67851836/93178767-489a8600-f767-11ea-83ad-45a46ddefcd5.png)

**Comment by okx-code** [comment]
Fixed in pre-release versions
