### ISSUE TITLE
Rankup money requirement

### ISSUE THREAD

**Issue by BruceFradgLee** [okx-code/Rankup3#5]
Hi, 
I'm having an issue where players are putting in /rankup and it's saying 'You need {Money} money to rankup'. Money isn't however one of the requirements i've placed in. Odd thing is it's working fine for the first few ranks but not the later few.
I've also tried to add it as a requirement but it still says they need money even when they have more than the specified amount.

Here's my rankups.yml: https://pastebin.com/n7GJP3u5

**Comment by okx-code** [comment]
You should change the requirements-not-met message for each rank.

Additionally, GitHub issues are for confirmed bugs. Ask in Discord first.
