### ISSUE TITLE
ERROR: when creating ranks

### ISSUE THREAD

**Issue by ThiagosFox** [okx-code/Rankup3#52]
I don't know what's going on, it's always giving an error, it only works with what is generated by the plugin, I'll leave the report log, and rankups.yml
latest.log
[rankups.txt](https://github.com/okx-code/Rankup3/files/5877581/rankups.txt)

**Comment by NicBOMB** [comment]
> I don't know what's going on, it's always giving an error, it only works with what is generated by the plugin, I'll leave the report log, and rankups.yml
> latest.log
> [rankups.txt](https://github.com/okx-code/Rankup3/files/5877581/rankups.txt)

Your log contained an IP address, so I have removed the link from your issue.

`[22:13:00] [Server thread/ERROR]: Cannot load plugins/Rankup/rankups.yml
org.bukkit.configuration.InvalidConfigurationException: sequence entries are not allowed here
 in 'string', line 7, column 17:
      requirements: - 'money 1000'
                    ^`
This was in the file.
It seems there are numerous user configuration errors in the rankups file. You should join the discord server and verify your purchase of premium support if you require it. This is not a bug nor feature request. /closed
