### ISSUE TITLE
Support for HDB heads?

### ISSUE THREAD

**Issue by Varatros** [okx-code/Rankup3#53]
Is support for the heads in head database (https://minecraft-heads.com/custom-heads/) going to be added or is already added?

**Comment by NicBOMB** [comment]
> 
> 
> Is support for the heads in head database (https://minecraft-heads.com/custom-heads/) going to be added or is already added?

What kind of support?
According to the FAQ of that website, you can already use commands to spawn those custom-heads.
Do you mean support for custom-heads as a requirement?

**Comment by okx-code** [comment]
Closing because #56 (custom item predicates) is more appropiate and versatile
