### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by Misterwingnut** [okx-code/Rankup3#54]
Landlubber:
  rank: 'default'
  next: 'landlubber'
  requirements:
    - 'money 2500'
  rankup:
    requirements-not-met:
      - '&cListen matey! I know u wanna stop scrubbing floors but u aint got enough money yet, you need 2.5k. Come back to me when u have that much!'
  commands:
    - 'Aye matey well done for being promoted from &f{&8FloorScrubber&f} to &f{&8Land&7Lubber&f}'
    - 'lp user {PLAYER} parent add Landlubber'
Swashbuckler:
  rank: 'landlubber'
  next: 'swashbuckler'
  requirements:
    - 'money 5000'
  rankup:
    requirements-not-met:
      - '&cRight Matey u already know the drill, but this time u need 5k to become a &7SwashBuckler&c. Come back to me when you have enough!'
  commands:
    - 'say {PLAYER} well done for ranking up from {landlubber} to {swashbuckler}!'
    - 'lp user {PLAYER} parent add landlubber' 
Mate:
  rank: 'swashbuckler'
  next: 'mate'
  requirements:
    - 'money 10000'
  rankup:
    requirements-not-met: |-
      &cCome on now Matey, you need to get used to this, Just come back to me when you have 10k!
 commands:
    - 'say {PLAYER} well done for ranking up from {swashbuckler} to {mate}!'
    - 'lp user {PLAYER} parent add mate'  
firstmate:
  rank: 'mate'
  next: 'first-mate'
  requirements:
    - 'money 50000'
  rankup:
    requirements-not-met: |-
      &cPutting it simply for you now &7YOU HAVNT GOT 50K!!!
  commands:
    - 'say {PLAYER} well done for ranking up from {mate} to {first-mate}!'
    - 'lp user {PLAYER} parent add firstmate'  
Buccaneer:
  rank: 'first-mate'
  next: 'buccaneer'
  requirements:
    - 'money 100000'
  rankup:
    requirements-not-met: |-
      &cIm not doing this everytime me matey, just get the 100k and come back to me.
  commands:
    - 'say {PLAYER} well done for ranking up from {first-mate} to {buccaneer}!'
    - - 'lp user {PLAYER} parent add buccaneer' 
Sea-dog:
  rank: 'buccaneer'
  next: 'sea-dog'
  requirements:
    - 'money 500000'
  rankup:
    requirements-not-met: |-
      &cListen &4Buccaneer &cif ya come to me one more time without the money i will be given ya the &0BLACK SPOT&C. Now go get the 500k!
  commands:
    - 'say {PLAYER} well done for ranking up from {buccaneer} to {sea-god}!'
    - 'lp user {PLAYER} parent add sea-dog'  
pirate:
  rank: 'sea-dog'
  next: 'pirate'
  requirements:
    - 'money 1500000'
  rankup:
    requirements-not-met: |-
      &cLucky for you i coulnt find a black spot giveya, But hoestly matey go get the 1.5m
  commands:
    - 'say {PLAYER} well done for ranking up from {sea-dog} to {pirate}!'
    - 'lp user {PLAYER} parent add pirate'  
pirate-captain:
  rank: 'pirate'
  next: 'pirate-captain'
  requirements:
    - 'money 5000000'
  rankup:
    requirements-not-met: |-
      &cI will get ye Davy Jones to pull ya into his locker if u dont pay the money, &4NOW GO GET THE 5m!!
  commands:
    - 'say {PLAYER} well done for ranking up from {pirate} to {pirate-captain}
    - 'lp user {PLAYER} parent add pirate-captain'
pirate-legend:
  rank: 'pirate-captain'
  next: 'pirate-legend'
  requirements:
    - 'money 30000000'
  rankup:
    requirements-not-met: |-
      &cYa are a captain now, u dont need telling to get the money, so get me the 30m
  commands:
    - 'say {PLAYER} well done for ranking up from {OLD_RANK} to {RANK}!'
    - 'lp user {PLAYER}	parent add pirate-legend
pirate lord:
  rank: 'pirate-legend'
  next: 'pirate-lord'
  requirements:
    - 'money 100000000'
  rankup:
    requirements-not-met: |-
      &cNow this is the most expensive rank out there, to get it you must have 100m, Good luck to you, See you in &4Davy Jones Locker!!!
  commands:
    - 'say {PLAYER} well done for ranking up from {pirate-legend} to {pirate-lord}
    - 'lp user {PLAYER} parent add pirate-lord'
    - 'bc {PLAYER} has become a &5PirateLord'

**Comment by Misterwingnut** [comment]
im getting this message "An internal error occurred while attempting to perform this command" and the console says this...

Caused by: java.lang.NullPointerException
        at sh.okx.rankup.ranks.RankList.getByPlayer(RankList.java:109) ~[?:?]
        at sh.okx.rankup.RankupHelper.checkRankup(RankupHelper.java:150) ~[?:?]
        at sh.okx.rankup.RankupHelper.checkRankup(RankupHelper.java:139) ~[?:?]
        at sh.okx.rankup.commands.RankupCommand.onCommand(RankupCommand.java:40) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-967]
        ... 19 more

**Comment by NicBOMB** [comment]
> 
> 
> Landlubber:
> rank: 'default'
> next: 'landlubber'
> requirements:
> - 'money 2500'
> rankup:
> requirements-not-met:
> - '&cListen matey! I know u wanna stop scrubbing floors but u aint got enough money yet, you need 2.5k. Come back to me when u have that much!'
> commands:
> - 'Aye matey well done for being promoted from &f{&8FloorScrubber&f} to &f{&8Land&7Lubber&f}'
> - 'lp user {PLAYER} parent add Landlubber'
> Swashbuckler:
> rank: 'landlubber'
> next: 'swashbuckler'
> requirements:
> - 'money 5000'
> rankup:
> requirements-not-met:
> - '&cRight Matey u already know the drill, but this time u need 5k to become a &7SwashBuckler&c. Come back to me when you have enough!'
> commands:
> - 'say {PLAYER} well done for ranking up from {landlubber} to {swashbuckler}!'
> - 'lp user {PLAYER} parent add landlubber'
> Mate:
> rank: 'swashbuckler'
> next: 'mate'
> requirements:
> - 'money 10000'
> rankup:
> requirements-not-met: |-
> &cCome on now Matey, you need to get used to this, Just come back to me when you have 10k!
> commands:
> - 'say {PLAYER} well done for ranking up from {swashbuckler} to {mate}!'
> - 'lp user {PLAYER} parent add mate'
> firstmate:
> rank: 'mate'
> next: 'first-mate'
> requirements:
> - 'money 50000'
> rankup:
> requirements-not-met: |-
> &cPutting it simply for you now &7YOU HAVNT GOT 50K!!!
> commands:
> - 'say {PLAYER} well done for ranking up from {mate} to {first-mate}!'
> - 'lp user {PLAYER} parent add firstmate'
> Buccaneer:
> rank: 'first-mate'
> next: 'buccaneer'
> requirements:
> - 'money 100000'
> rankup:
> requirements-not-met: |-
> &cIm not doing this everytime me matey, just get the 100k and come back to me.
> commands:
> - 'say {PLAYER} well done for ranking up from {first-mate} to {buccaneer}!'
> - - 'lp user {PLAYER} parent add buccaneer'
> Sea-dog:
> rank: 'buccaneer'
> next: 'sea-dog'
> requirements:
> - 'money 500000'
> rankup:
> requirements-not-met: |-
> &cListen &4Buccaneer &cif ya come to me one more time without the money i will be given ya the &0BLACK SPOT&C. Now go get the 500k!
> commands:
> - 'say {PLAYER} well done for ranking up from {buccaneer} to {sea-god}!'
> - 'lp user {PLAYER} parent add sea-dog'
> pirate:
> rank: 'sea-dog'
> next: 'pirate'
> requirements:
> - 'money 1500000'
> rankup:
> requirements-not-met: |-
> &cLucky for you i coulnt find a black spot giveya, But hoestly matey go get the 1.5m
> commands:
> - 'say {PLAYER} well done for ranking up from {sea-dog} to {pirate}!'
> - 'lp user {PLAYER} parent add pirate'
> pirate-captain:
> rank: 'pirate'
> next: 'pirate-captain'
> requirements:
> - 'money 5000000'
> rankup:
> requirements-not-met: |-
> &cI will get ye Davy Jones to pull ya into his locker if u dont pay the money, &4NOW GO GET THE 5m!!
> commands:
> - 'say {PLAYER} well done for ranking up from {pirate} to {pirate-captain}
> - 'lp user {PLAYER} parent add pirate-captain'
> pirate-legend:
> rank: 'pirate-captain'
> next: 'pirate-legend'
> requirements:
> - 'money 30000000'
> rankup:
> requirements-not-met: |-
> &cYa are a captain now, u dont need telling to get the money, so get me the 30m
> commands:
> - 'say {PLAYER} well done for ranking up from {OLD_RANK} to {RANK}!'
> - 'lp user {PLAYER} parent add pirate-legend
> pirate lord:
> rank: 'pirate-legend'
> next: 'pirate-lord'
> requirements:
> - 'money 100000000'
> rankup:
> requirements-not-met: |-
> &cNow this is the most expensive rank out there, to get it you must have 100m, Good luck to you, See you in &4Davy Jones Locker!!!
> commands:
> - 'say {PLAYER} well done for ranking up from {pirate-legend} to {pirate-lord}
> - 'lp user {PLAYER} parent add pirate-lord'
> - 'bc {PLAYER} has become a &5PirateLord'

This is not helpful. The original file formatting has been removed during your copy paste, or your entire file was formatted incorrectly. Please share the original file or use a paste service like https://pastie.io/ to share your file. Also join the discord server and verify your spigot username for live support.

**Comment by NicBOMB** [comment]
It also seems like you're using commands to add luckperms groups manually. Are you using [`permission-rankup: true`](https://github.com/okx-code/Rankup3/blob/2bb17a0b714c36f0985a2973be849964766d8b98/src/main/resources/config.yml#L37-L43)? I suggest looking at this https://github.com/okx-code/Rankup3/wiki/FAQ#do-i-need-to-add-a-command-to-manually-change-a-players-group

**Comment by Misterwingnut** [comment]
https://pastie.io/xuhxbp.sql

Is that better, that is the ranking up I have tried to do. I can get the errors for you a little later.

**Comment by NicBOMB** [comment]
That's still incorrect. Use the discord server if you require further assistance.
