### ISSUE TITLE
No RGB support for "requirements-not-met:" and "confirmation:" when the hex code is located in the DisplayName

### ISSUE THREAD

**Issue by Gqby** [okx-code/Rankup3#57]
Hello, it looks like there's a bug in the locale and rankup file, where there isn't any rgb support for "requirements-not-met:" and "confirmation:" when the hex code is located the rank display-name. Here is how looks my eng.yml :

`rankup:`
`  requirements-not-met: |-`
`      &4&m+                                       +`
`      &cYou need`
`      &c- &d&l$%rankup_money_formatted% &c&l- &b[%progress_bar_{PERCENT_DONE money}_c:&d|_p:&d|_r:&3|_l:20_m:100_fullbar:&a&lCompleted!%&b]`
`      &c- &d&l%rankup_requirement_xp-level% &5&lXP levels &c&l- &b[%progress_bar_{PERCENT_DONE xp-level}_c:&d|_p:&d|_r:&3|_l:20_m:100_fullbar:&a&lCompleted!%&b]`
`      &cto rankup from &7{OLD_RANK_NAME}&c to &d{RANK_NAME}&c!
      &4&m+                                       +`
`  no-rankup: "&eYou are at the highest rank."`
`  success-public: "&a{PLAYER} &ehas ranked up to: &d{RANK_NAME}!"`
`  success-private: "&aYou have ranked up to: &d{RANK_NAME}!"`
`  confirmation: |-`
`    &eAre you sure you want to rankup to &a{RANK_NAME}&e?`
`    &eType &c/rankup &eagain to confirm.`
`  title: "Rankup to {RANK_NAME}"`

`  must-prestige: "&cYou must prestige to /rankup further!"`

**Comment by okx-code** [comment]
Fixed in 3.12 due to reordering of text processing
