### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by gordonchew** [okx-code/Rankup3#60]
Can anyone teach me how?
https://gyazo.com/4bda531344be81936e003cd27d581c24
![Untitled](https://user-images.githubusercontent.com/84636569/119234418-645cf400-bb60-11eb-9be5-0ceff24842e8.png)

Why it say An internal error occcured while attempting to perform this command?
Where did i did wrong?

**Comment by flurbudurbur** [comment]
it should say in the console. though please ask for support in the [Discord server](https://discord.gg/2yPsJpHs)
