### ISSUE TITLE
Request: Text Match for PlaceholderAPI Requirement

### ISSUE THREAD

**Issue by austin4195** [okx-code/Rankup3#61]
I noticed when I was reading the new Rankup 3.12 wiki that the PlaceholderAPI Requirement requires the use of a hard number. This is potentially a problem for the system I was doing where using %discordsrv_islinked% resolves to a "yes" or "no"

Would it be possible to modify the PlaceholderAPI requirement to accept when == is used an exact text match?

**Comment by okx-code** [comment]
This is already the functionality of the placeholder requirement, for example `placeholder %discordsrv_islinked% = yes`

**Comment by austin4195** [comment]
I do apologize for the misunderstanding. From reading the wiki, it sounded like it had to resolve to a number for the placeholderapi stuff to work correctly.

**Comment by okx-code** [comment]
A single `=` will do an exact text match, all other operations including `==` will compare by first converting to a number.
