### ISSUE TITLE
RankupPlaceholderTest > testQuotientAndPercent() FAILED

### ISSUE THREAD

**Issue by Bautigarzabal** [okx-code/Rankup3#68]
When i try to build Rankup3 the error

> RankupPlaceholderTest > testQuotientAndPercent() FAILED
    org.opentest4j.AssertionFailedError at RankupPlaceholderTest.java:45

Appears, what can i do to solve it?

Index.html: (i can't upload a .html in github)
[index.zip](https://github.com/okx-code/Rankup3/files/6850923/index.zip)

**Comment by okx-code** [comment]
Have you modified any of the files? What does the test output (when it runs the assertation)?
