### ISSUE TITLE
Rankup 1.14.1

### ISSUE THREAD

**Issue by srrawr11** [okx-code/Rankup3#77]
Paper 1.19.4
Java edition
Plugin version: 1.14.1

Hi, there is a problem.. sometimes my users without any reason/spam/error in the console.. they loose the rankup..
I do not know how.. but there are no spam errors in the console..

**Comment by okx-code** [comment]
Ask for support in the discord, there is not enough information here

**Comment by srrawr11** [comment]
> Ask for support in the discord, there is not enough information here

Sorry for the reaply..

There are no errors in the console.. just sometimes my users lost the ranks.. I do not know why..
