### ISSUE TITLE
Is not a issue , but a need.

### ISSUE THREAD

**Issue by MihaiCiornei** [okx-code/Rankup3#81]
Everything works great, I bought version 3.14.4, just a small problem. I would like on the server to make the ranks depend on time, everything is ok, the problem is that when you rank up, the required time is reduced from the time you played on the server, so what do you do if you want to certain level you want the player to rank up to 200 hours, then 300, instead of 300 hours played, the player will need 500....
![rankup error ](https://github.com/okx-code/Rankup3/assets/101269216/f537c7a5-3e9f-48ee-952c-4d0a8acbcc22)

**Comment by flurbudurbur** [comment]
Hi there, I've come up with 2 solutions to you which wouldn't involve an update to Rankup and can be now:

1. Add the following command after each rankup that uses the playtime-minutes requirement:
`- "pru playtime add {{ player }} -{{ rank.req('playtime-minutes').total | simple }}"`.

2. I've made a code snippet you can find in our wiki. https://okx.sh/rankup/Text-Templating/Snippets.html

With this you should be pretty set. If you have any questions, please reach out through Discord as I'm more active there.
